Repository octokit/plugin-create-or-update-text-file.js, pull requests merged in 2023-06, with the labels that each got.

#161 fix(build): switch to esbuild in place of pika
  package-lock.json
  package.json
  scripts/build.mjs
  src/compose-create-or-update-text-file.ts
  src/index.ts
  src/types.ts
  test/create-or-update-text-file.test.ts
  test/errors.test.ts
  test/tsconfig.test.json
  tsconfig.json
Labels: Type: Maintenance

#154 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package.json
  scripts/build.mjs
Labels: Type: Breaking change, Type: Maintenance

#164 docs: replace references to Skypack CDN with esm.sh
  README.md
Labels: Type: Documentation
